spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://contestapp-postgres:5432/contestapp
    username: user
    password: a1234
    driver-class-name: org.postgresql.Driver
    schema: user_service
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: user_service
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  rabbitmq:
    host: contestapp-rabbitmq
    port: 5672
    username: user
    password: a1234

server:
  port: 8081

logging:
  level:
    com.contestapp.userservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 