spring:
  application:
    name: ai-service

  datasource:
    url: jdbc:postgresql://contestapp-postgres:5432/contestapp
    username: user
    password: a1234
    driver-class-name: org.postgresql.Driver
    schema: ai_service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ai_service
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  rabbitmq:
    host: contestapp-rabbitmq
    port: 5672
    username: user
    password: a1234

server:
  port: 8087

logging:
  level:
    com.contestapp.aiservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 